<script lang="ts">
	import { page } from '$app/stores';
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { browser } from '$app/environment';
	import { auth, db } from '$lib/firebase';
	import { onAuthStateChanged } from 'firebase/auth';
	import { doc, getDoc, deleteDoc, updateDoc } from 'firebase/firestore';

	let trip: any = null;
	let loading = true;
	let currentUser: any = null;
	let error = '';
	let showDeleteConfirm = false;
	let deleting = false;

	$: tripId = $page.params.id;

	onMount(() => {
		if (!browser || !auth || !db) {
			loading = false;
			return;
		}

		const unsubscribe = onAuthStateChanged(auth, async (user) => {
			currentUser = user;
			if (!user) {
				goto('/get-started');
				return;
			}

			try {
				const tripRef = doc(db, 'users', user.uid, 'trips', tripId);
				const tripDoc = await getDoc(tripRef);
				
				if (tripDoc.exists()) {
					trip = { id: tripDoc.id, ...tripDoc.data() };
				} else {
					error = 'Trip not found';
				}
			} catch (err) {
				console.error('Error fetching trip:', err);
				error = 'Failed to load trip';
			}

			loading = false;
		});

		return () => unsubscribe();
	});

	function formatDate(date: any): string {
		if (!date) return '';
		const d = date.toDate ? date.toDate() : new Date(date);
		return d.toLocaleDateString('en-US', { 
			year: 'numeric', 
			month: 'long', 
			day: 'numeric' 
		});
	}

	function getTripStatus(trip: any): string {
		const now = new Date();
		const start = trip.startDate?.toDate ? trip.startDate.toDate() : new Date(trip.startDate);
		const end = trip.endDate?.toDate ? trip.endDate.toDate() : new Date(trip.endDate);
		
		if (now < start) return 'upcoming';
		if (now > end) return 'completed';
		return 'ongoing';
	}

	async function handleDelete() {
		if (!currentUser || !db || !tripId) return;
		
		deleting = true;
		try {
			await deleteDoc(doc(db, 'users', currentUser.uid, 'trips', tripId));
			goto('/dashboard/trips');
		} catch (err) {
			console.error('Error deleting trip:', err);
			error = 'Failed to delete trip';
		}
		deleting = false;
		showDeleteConfirm = false;
	}

	async function exportToPDF() {
		if (!trip) return;
		
		// Dynamic import jspdf
		const { jsPDF } = await import('jspdf');
		
		const doc = new jsPDF();
		
		// Title
		doc.setFontSize(20);
		doc.setTextColor(10, 30, 60);
		doc.text(trip.name || 'Trip Details', 20, 20);
		
		// Details
		doc.setFontSize(12);
		doc.setTextColor(60, 60, 60);
		
		doc.text(`Destination: ${trip.destination || 'N/A'}`, 20, 35);
		doc.text(`Start Date: ${formatDate(trip.startDate)}`, 20, 45);
		doc.text(`End Date: ${formatDate(trip.endDate)}`, 20, 55);
		doc.text(`Status: ${getTripStatus(trip)}`, 20, 65);
		
		if (trip.notes) {
			doc.text('Notes:', 20, 80);
			doc.setFontSize(10);
			const splitNotes = doc.splitTextToSize(trip.notes, 170);
			doc.text(splitNotes, 20, 90);
		}
		
		// Footer
		doc.setFontSize(8);
		doc.setTextColor(150, 150, 150);
		doc.text('Generated by VERYNICE.kz', 20, 280);
		
		doc.save(`${trip.name || 'trip'}-details.pdf`);
	}

	async function exportToCalendar() {
		if (!trip) return;
		
		// Dynamic import ical-generator
		const ical = await import('ical-generator');
		
		const calendar = ical.createCalendar({
			name: `${trip.name} - VERYNICE.kz`,
			description: `Trip to ${trip.destination}`
		});
		
		const startDate = trip.startDate?.toDate ? trip.startDate.toDate() : new Date(trip.startDate);
		const endDate = trip.endDate?.toDate ? trip.endDate.toDate() : new Date(trip.endDate);
		
		calendar.createEvent({
			start: startDate,
			end: endDate,
			summary: trip.name,
			location: trip.destination,
			description: trip.notes || `Trip to ${trip.destination} planned with VERYNICE.kz`
		});
		
		// Trigger download
		const calendarString = calendar.toString();
		const blob = new Blob([calendarString], { type: 'text/calendar;charset=utf-8' });
		const url = URL.createObjectURL(blob);
		const link = document.createElement('a');
		link.href = url;
		link.download = `${trip.name || 'trip'}.ics`;
		document.body.appendChild(link);
		link.click();
		document.body.removeChild(link);
		URL.revokeObjectURL(url);
	}
</script>

<svelte:head>
	<title>{trip?.name || 'Trip Details'} — VERYNICE.kz</title>
	<meta name="description" content="View trip details" />
</svelte:head>

<div class="trip-detail-page">
	<header class="page-header">
		<div class="header-content">
			<a href="/dashboard/trips" class="back-link">
				<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
					<path d="M19 12H5M12 19l-7-7 7-7"/>
				</svg>
				Back to Trips
			</a>
			<div class="header-actions">
				<button class="btn-export" on:click={exportToPDF} title="Export to PDF">
					<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
						<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
						<polyline points="7 10 12 15 17 10"></polyline>
						<line x1="12" y1="15" x2="12" y2="3"></line>
					</svg>
					PDF
				</button>
				<button class="btn-export" on:click={exportToCalendar} title="Export to Calendar">
					<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
						<rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
						<line x1="16" y1="2" x2="16" y2="6"></line>
						<line x1="8" y1="2" x2="8" y2="6"></line>
						<line x1="3" y1="10" x2="21" y2="10"></line>
					</svg>
					Calendar
				</button>
				<button class="btn-delete" on:click={() => showDeleteConfirm = true}>
					<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
						<polyline points="3 6 5 6 21 6"></polyline>
						<path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
					</svg>
					Delete
				</button>
			</div>
		</div>
	</header>

	<main class="page-content">
		{#if loading}
			<div class="loading-state">
				<div class="spinner"></div>
				<p>Loading trip details...</p>
			</div>
		{:else if error}
			<div class="error-state">
				<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
					<circle cx="12" cy="12" r="10"></circle>
					<line x1="12" y1="8" x2="12" y2="12"></line>
					<line x1="12" y1="16" x2="12.01" y2="16"></line>
				</svg>
				<h2>Error</h2>
				<p>{error}</p>
				<a href="/dashboard/trips" class="btn-primary">Back to Trips</a>
			</div>
		{:else if trip}
			<div class="trip-details">
				<div class="trip-header">
					<h1>{trip.name}</h1>
					<span class="status-badge {getTripStatus(trip)}">{getTripStatus(trip)}</span>
				</div>

				<div class="detail-grid">
					<div class="detail-card">
						<div class="detail-icon">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
								<path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"></path>
								<circle cx="12" cy="10" r="3"></circle>
							</svg>
						</div>
						<div class="detail-content">
							<span class="detail-label">Destination</span>
							<span class="detail-value">{trip.destination}</span>
						</div>
					</div>

					<div class="detail-card">
						<div class="detail-icon">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
								<rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
								<line x1="16" y1="2" x2="16" y2="6"></line>
								<line x1="8" y1="2" x2="8" y2="6"></line>
								<line x1="3" y1="10" x2="21" y2="10"></line>
							</svg>
						</div>
						<div class="detail-content">
							<span class="detail-label">Dates</span>
							<span class="detail-value">{formatDate(trip.startDate)} - {formatDate(trip.endDate)}</span>
						</div>
					</div>
				</div>

				{#if trip.notes}
					<div class="notes-section">
						<h2>Notes</h2>
						<p>{trip.notes}</p>
					</div>
				{/if}

				<div class="trip-metadata">
					<span>Created: {formatDate(trip.createdAt)}</span>
					{#if trip.updatedAt}
						<span>Last updated: {formatDate(trip.updatedAt)}</span>
					{/if}
				</div>
			</div>
		{/if}
	</main>

	<!-- Delete Confirmation Modal -->
	{#if showDeleteConfirm}
		<div class="modal-overlay" on:click={() => showDeleteConfirm = false} role="button" tabindex="0" on:keypress={(e) => e.key === 'Escape' && (showDeleteConfirm = false)}>
			<div class="modal-content" on:click|stopPropagation role="dialog" aria-modal="true">
				<h2>Delete Trip?</h2>
				<p>Are you sure you want to delete "{trip?.name}"? This action cannot be undone.</p>
				<div class="modal-actions">
					<button class="btn-secondary" on:click={() => showDeleteConfirm = false}>Cancel</button>
					<button class="btn-danger" on:click={handleDelete} disabled={deleting}>
						{#if deleting}
							<span class="spinner-small"></span>
							Deleting...
						{:else}
							Delete Trip
						{/if}
					</button>
				</div>
			</div>
		</div>
	{/if}
</div>

<style>
	.trip-detail-page {
		min-height: 100vh;
		background: #f8f9fa;
	}

	.page-header {
		background: #0a1e3c;
		padding: 1.5rem 0;
	}

	.header-content {
		max-width: 900px;
		margin: 0 auto;
		padding: 0 2rem;
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 1rem;
	}

	.back-link {
		color: rgba(255,255,255,0.8);
		text-decoration: none;
		display: flex;
		align-items: center;
		gap: 0.5rem;
		font-size: 0.9rem;
		transition: color 0.2s;
	}

	.back-link:hover {
		color: white;
	}

	.header-actions {
		display: flex;
		gap: 0.75rem;
	}

	.btn-export, .btn-delete {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.5rem 1rem;
		border-radius: 6px;
		font-size: 0.9rem;
		font-weight: 500;
		cursor: pointer;
		transition: all 0.2s;
		border: none;
	}

	.btn-export {
		background: rgba(255,255,255,0.1);
		color: white;
	}

	.btn-export:hover {
		background: rgba(255,255,255,0.2);
	}

	.btn-delete {
		background: #dc3545;
		color: white;
	}

	.btn-delete:hover {
		background: #c82333;
	}

	.page-content {
		max-width: 900px;
		margin: 0 auto;
		padding: 2rem;
	}

	.loading-state, .error-state {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		padding: 4rem 2rem;
		text-align: center;
	}

	.spinner {
		width: 40px;
		height: 40px;
		border: 3px solid #e9ecef;
		border-top-color: #00b894;
		border-radius: 50%;
		animation: spin 0.8s linear infinite;
		margin-bottom: 1rem;
	}

	@keyframes spin {
		to { transform: rotate(360deg); }
	}

	.error-state svg {
		color: #dc3545;
		margin-bottom: 1rem;
	}

	.error-state h2 {
		color: #2d3436;
		margin-bottom: 0.5rem;
	}

	.error-state p {
		color: #6c757d;
		margin-bottom: 1.5rem;
	}

	.btn-primary {
		background: #00b894;
		color: white;
		padding: 0.75rem 1.5rem;
		border-radius: 8px;
		text-decoration: none;
		font-weight: 500;
	}

	.trip-details {
		background: white;
		border-radius: 12px;
		padding: 2rem;
		box-shadow: 0 2px 8px rgba(0,0,0,0.08);
	}

	.trip-header {
		display: flex;
		align-items: center;
		gap: 1rem;
		margin-bottom: 2rem;
		padding-bottom: 1.5rem;
		border-bottom: 1px solid #e9ecef;
	}

	.trip-header h1 {
		font-size: 1.75rem;
		color: #2d3436;
		margin: 0;
	}

	.status-badge {
		padding: 0.35rem 1rem;
		border-radius: 20px;
		font-size: 0.85rem;
		font-weight: 500;
		text-transform: capitalize;
	}

	.status-badge.upcoming {
		background: #e3f2fd;
		color: #1976d2;
	}

	.status-badge.ongoing {
		background: #e8f5e9;
		color: #388e3c;
	}

	.status-badge.completed {
		background: #f5f5f5;
		color: #757575;
	}

	.detail-grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
		gap: 1.5rem;
		margin-bottom: 2rem;
	}

	.detail-card {
		display: flex;
		align-items: center;
		gap: 1rem;
		padding: 1.25rem;
		background: #f8f9fa;
		border-radius: 10px;
	}

	.detail-icon {
		color: #00b894;
	}

	.detail-content {
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
	}

	.detail-label {
		font-size: 0.85rem;
		color: #6c757d;
	}

	.detail-value {
		font-size: 1rem;
		font-weight: 500;
		color: #2d3436;
	}

	.notes-section {
		margin-bottom: 2rem;
	}

	.notes-section h2 {
		font-size: 1.25rem;
		color: #2d3436;
		margin-bottom: 1rem;
	}

	.notes-section p {
		color: #495057;
		line-height: 1.6;
		white-space: pre-wrap;
	}

	.trip-metadata {
		display: flex;
		gap: 2rem;
		font-size: 0.85rem;
		color: #6c757d;
		padding-top: 1.5rem;
		border-top: 1px solid #e9ecef;
	}

	/* Modal */
	.modal-overlay {
		position: fixed;
		inset: 0;
		background: rgba(0,0,0,0.5);
		display: flex;
		align-items: center;
		justify-content: center;
		z-index: 1000;
	}

	.modal-content {
		background: white;
		padding: 2rem;
		border-radius: 12px;
		max-width: 400px;
		width: 90%;
	}

	.modal-content h2 {
		font-size: 1.25rem;
		color: #2d3436;
		margin-bottom: 0.75rem;
	}

	.modal-content p {
		color: #6c757d;
		margin-bottom: 1.5rem;
	}

	.modal-actions {
		display: flex;
		gap: 1rem;
		justify-content: flex-end;
	}

	.btn-secondary {
		background: #f8f9fa;
		color: #6c757d;
		padding: 0.75rem 1.25rem;
		border-radius: 8px;
		font-weight: 500;
		border: none;
		cursor: pointer;
	}

	.btn-secondary:hover {
		background: #e9ecef;
	}

	.btn-danger {
		background: #dc3545;
		color: white;
		padding: 0.75rem 1.25rem;
		border-radius: 8px;
		font-weight: 500;
		border: none;
		cursor: pointer;
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}

	.btn-danger:hover:not(:disabled) {
		background: #c82333;
	}

	.btn-danger:disabled {
		opacity: 0.7;
		cursor: not-allowed;
	}

	.spinner-small {
		width: 16px;
		height: 16px;
		border: 2px solid rgba(255,255,255,0.3);
		border-top-color: white;
		border-radius: 50%;
		animation: spin 0.8s linear infinite;
	}

	@media (max-width: 600px) {
		.header-actions {
			flex-wrap: wrap;
		}
		
		.detail-grid {
			grid-template-columns: 1fr;
		}
	}
</style>