import { sequence } from '@sveltejs/kit/hooks';
import type { Handle } from '@sveltejs/kit';
import * as Sentry from '@sentry/sveltekit';
import { verifyFirebaseSessionCookie } from '$lib/server/sessionAuth';

// Sentry.init() is called in src/instrumentation.server.ts (loaded first via experimental.instrumentation.server).
// Do NOT call Sentry.init() here — a second init with undefined DSN re-registers the OTel TracerProvider and throws.

export const handleError = Sentry.handleErrorWithSentry();

// ── Centralized auth middleware ──────────────────────────────────────────
// Parses the session cookie on every request and attaches user context to
// event.locals. Routes can then check event.locals instead of calling
// verifyFirebaseSessionCookie individually — ensuring no route is
// accidentally left unprotected.
const authHandle: Handle = async ({ event, resolve }) => {
	const sessionCookie = event.cookies.get('__session');
	const session = await verifyFirebaseSessionCookie(sessionCookie);

	event.locals.isAuthenticated = session.isAuthenticated;
	event.locals.uid = session.uid;
	event.locals.role = session.role;

	return resolve(event);
};

const securityHandle: Handle = async ({ event, resolve }) => {
	// Redirect old /traveller-portal URL to new /get-started URL
	if (event.url.pathname === '/traveller-portal' || event.url.pathname === '/traveller-portal/') {
		return new Response(null, {
			status: 301,
			headers: { Location: '/get-started' }
		});
	}

	const response = await resolve(event);

	// Security headers
	response.headers.set('X-Content-Type-Options', 'nosniff');
	response.headers.set('X-Frame-Options', 'DENY');
	response.headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');
	response.headers.set('Cross-Origin-Opener-Policy', 'same-origin-allow-popups');
	response.headers.set('Cross-Origin-Resource-Policy', 'same-site');
	response.headers.set('Permissions-Policy', 'camera=(), microphone=(), geolocation=()');
	if (event.url.protocol === 'https:') {
		response.headers.set('Strict-Transport-Security', 'max-age=31536000; includeSubDomains; preload');
	}

	// Content-Security-Policy is generated by SvelteKit's csp engine (svelte.config.js csp.mode='auto').
	// SvelteKit injects the full policy — including per-request nonces for SSR and build-time hashes
	// for prerendered pages — before this handle runs. Do not set it here.
	response.headers.set('X-DNS-Prefetch-Control', 'on');

	// Cache control
	if (event.url.pathname.startsWith('/_app/') || event.url.pathname.startsWith('/vendor/')) {
		response.headers.set('Cache-Control', 'public, max-age=31536000, immutable');
	} else if (event.url.pathname.startsWith('/api/auth/')) {
		// Auth endpoints must never be cached — they set/clear session cookies.
		// no-store prevents every layer (browser, CDN, proxy) from retaining the response.
		response.headers.set('Cache-Control', 'no-store, no-cache, must-revalidate');
		response.headers.set('Pragma', 'no-cache');
	} else if (!event.url.pathname.startsWith('/api/')) {
		response.headers.set('Cache-Control', 'public, max-age=300, s-maxage=300, must-revalidate');
	}

	return response;
};

export const handle = sequence(Sentry.sentryHandle(), authHandle, securityHandle);
